NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

users:
    type:     rest
    resource: AppBundle\Controller\UsersController

photos:
    type:   rest
    resource: Appbundle\Controller\PhotoController

testcases:
    type:   rest
    resource: AppBundle\Controller\TestCaseController